openapi: 3.0.0
info:
  title: Contrato OpenAPI para Endpoint de Cachorro
  version: 1.0.0
paths:
  /cachorros:
    post:
      summary: Enviar informações sobre um cachorro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cachorro'
      responses:
        '200':
          description: Sucesso ao enviar as informações do cachorro
components:
  schemas:
    Cachorro:
      type: object
      properties:
        cor:
          type: string
          description: Cor do cachorro
        raca:
          type: string
          description: Raça do cachorro
        idade:
          type: integer
          description: Idade do cachorro em anos
        doencas_geneticas:
          type: array
          items:
            type: string
          description: Lista de doenças genéticas do cachorro